



Vagrant.configure("2") do |config|
  config.vm.box = "generic/arch"
  config.vm.network "private_network", ip: "192.168.56.101"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = 2
    # Increase disk size to 50GB to accommodate large Python packages 
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end
  config.vm.provision "shell", path: "provision_vagrant.sh"
  
  # Configure disk size
  config.vm.disk :disk, size: "50GB", primary: true
  
  # sync folder: host repo -> /vagrant in guest
end
