Vagrant.configure("2") do |config|
  config.vm.box = "generic/arch"
  config.vm.network "private_network", ip: "192.168.56.101"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = 2
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end

  config.vm.provision "shell", path: "provision_vagrant.sh"
  
  # Configure disk size
  config.vm.disk :disk, size: "50GB", primary: true

  # Add a shared folder
  config.vm.synced_folder "~/Public/cdg/gan", "/home/vagrant/shared", 
      owner: "vagrant", group: "vagrant", mount_options: ["dmode=775","fmode=664"]
end
